### ISSUE TITLE
Use MNI coordinates to visualize electrodes (instead of tkRAS)

### ISSUE THREAD

**Issue by ErnestJohnston** [dipterix/threeBrain#32]
I am using threeBrain to visualize intracranial electrodes that I have already localized. I used SPM12 for co-registration, which produced electrode coordinates in `native` and `MNI` space (but not `tkRAS` since I did not use Freesurfer). 

Your tutorial states that the required `Coord_x`, `Coord_y`, `Coord_z` are specified in `tkRAS` coordinates. Is there an alternative way for me to visualize the electrodes using only `MNI` coordinates?

**Comment by dipterix** [comment]
Yess! 

Here's the reference in case you want to know the details: https://surfer.nmr.mgh.harvard.edu/fswiki/CoordinateSystems

> 2. I have an RAS point on the surface (tkrR tkrA tkrS) ("Vertex RAS" from tksurfer) and want to compute the MNI305 RAS that corresponds to this point:
> MNI305RAS = TalXFM * Norig * inv(Torig) * [tkrR tkrA tkrS 1]' 

You can easily obtain those matrices (suppose you have created `brain` object via `threeBrain` or `raveio`) via `brain$xfm`, `brain$Torig`, and `brain$Norig`

```r
# For debug use
# brain <- raveio::rave_brain("demo/DemoSubject")
# MNI305 <- read.csv("~/Downloads/mni.csv")

# Assume brain and MNI305 exist, and MNI305 is a nx3 matrix, where
# n is the number of electrode (contacts)

# Convert to 4xn matrix
MNI305_ <- rbind(t(as.matrix(MNI305)), 1)

# MNI305RAS = TalXFM * Norig * inv(Torig) * [tkrR tkrA tkrS 1]' 
# All we need to do is to reverse this transform

# matrix from tkrRAS to MNI305
# This is wrong: tkr_to_mni305 <- brain$xfm %*% brain$Torig %*% brain$Norig

# Corrected on Mar-22, 2023. See comment below
tkr_to_mni305 <- brain$xfm %*% brain$Norig %*% solve(brain$Torig)

# transform from MNI to tkrRAS
tkrRAS <- solve(tkr_to_mni305) %*% MNI305_

electrode_table <- data.frame(
  Electrode = seq_len(ncol(tkrRAS)),
  Coord_x = tkrRAS[1, ],
  Coord_y = tkrRAS[2, ],
  Coord_z = tkrRAS[3, ],
  Label = "Unlabeled",
  MNI305_x = MNI305_[1, ],
  MNI305_y = MNI305_[2, ],
  MNI305_z = MNI305_[3, ]
)

print(electrode_table)

#>   Electrode  Coord_x   Coord_y  Coord_z     Label  MNI305_x  MNI305_y
#> 1         1 8.557298 -19.15868 233.8734 Unlabeled -1.102229 0.8600933
#>   MNI305_z
#> 1 1.331195
```

#### Caveat

1. Sometimes people use `MNI152` as "mni" coordinate. If this is your case, please make sure you transform MNI152 to MNI305 first (see the FreeSurfer reference above). The transform matrix can be found in `threeBrain:::MNI305_to_MNI152`. It's a fixed transform

2. If you are using [RAVE](https://rave.wiki), there is a function for this purpose (`raveio::import_electrode_table`)

Please feel free to ask me more questions if needed.

**Comment by dipterix** [comment]
Forgot to say... since `threeBrain` is written in R and many neuroscientists are not familiar with R, please feel free to email slack@rave.wiki. We will add you to our slack channel for further support (questions via email, zoom, or slack)

**Comment by ErnestJohnston** [comment]
Thank you for this helpful response! I have `MNI152` coordinates, so I tried converting `MNI152` -> `MNI305` -> `tkrRAS` as you suggested.

However, the transformation you posted places the electrodes far above the brain model. To troubleshoot, I inspected the `raveio::import_electrode_table()` function, which has an `MNI152` -> `tkrRAS` conversion that is different in two ways. 

First, the order of matrix multiplication is `Torig, Norig, xfm, MNI305` (instead of `xfm, Torig, Norig, MNI305`). Second, it does not use `solve()` on `Torig`. An excerpt is below:

```R
} else if (has_mni152) {
  catgl("MNI-152 detected! MNI-152 -> tkrRAS")
  tmp <- new_tbl[, paste0("MNI152_", c("x", "y", "z"))]
  tmp <- t(cbind(data.matrix(tmp), 1))
  invalids <- colSums(tmp == 0) == 3
  tkRAS <- t(brain$Torig %*% solve(brain$Norig) %*%
               solve(brain$xfm) %*% solve(MNI305_to_MNI152) %*%
               tmp)[, c(1, 2, 3)]
  tkRAS[invalids, ] <- 0
  new_tbl[, paste0("Coord_", c("x", "y", "z"))] <- tkRAS
```

I then specified the transformation below based on what was in `import_electrode_table()`. The electrodes now look approximately correct when I visualize them with `plot(brain)` -- does the transformation look correct to you?

```R
# Load electrode info
electrode_info <- read.csv(electrode_info_file_path)

# Extract MNI152 coordinates and format for conversion
mni152 <- electrode_info[, c('MNI152_x', 'MNI152_y', 'MNI152_z')]
mni152 <- rbind(t(as.matrix(mni152)), 1)

# Convert MNI152 to MNI305
mni305 <- solve(threeBrain:::MNI305_to_MNI152) %*% mni152

# Convert MNI305 to tkrRAS
tkrRAS <- brain$Torig %*% solve(brain$Norig) %*% solve(brain$xfm) %*% mni305
```

Another related question: I do not have `Freesurfer` files, so I am using the included `N27` template for my brain object as below. Since the `xfm`, `Torig`, and `Norig` matrices are derived from that object, will the transformation still be valid?

```R
n27_path <- file.path(default_template_directory(), "N27")

brain <- freesurfer_brain2(fs_subject_folder = n27_path,
                           subject_name = 'N27', 
                           surface_types = c('pial', 'white', 'smoothwm'),
                           atlas_types = c('aparc.DKTatlas+aseg'))
```

**Comment by dipterix** [comment]
Oh my bad. my transform in the initial comment was wrong. You are right!

As for the second question, yes the transform will still be valid since MNI is shared across subjects.

Also a tip: for template options, you can use `fsaverage` as well if N27 is not good for your purpose (N27 is a Collin's brain)

```
threeBrain::download_template_subject("fsaverage")

# Now you can replace N27 with fsaverage in your code
```

**Comment by dipterix** [comment]
Ah, also forgot to say, I wrote a new function `threeBrain::threeBrain` to replace `freesurfer_brain2` but haven't updated the documents yet. This new function does not need to cache the freesurfer files.

**Comment by dipterix** [comment]
For those who reach to this issue. I wrote a script that takes in BIDS electrode file (in MNI305 space) and visualize on template brain (N27 or fsaverage). 

https://github.com/rave-ieeg/rave-gists/blob/main/visualize-mni-in-template-brain.R

@ErnestJohnston Please feel free to re-open this issue if you have further questions. I'm closing this issue for now :)
